FROM nginx:latest
LABEL maintainer="Stephen Newby <stephen.j.newby@gmail.com>"
COPY softy-pinko-front-end /var/www/html/softy-pinko-front-end
COPY softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf
